require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConsulsController do

  # This should return the minimal set of attributes required to create a valid
  # Consul. As you add validations to Consul, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "data" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConsulsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all consuls as @consuls" do
      consul = Consul.create! valid_attributes
      get :index, {}, valid_session
      assigns(:consuls).should eq([consul])
    end
  end

  describe "GET show" do
    it "assigns the requested consul as @consul" do
      consul = Consul.create! valid_attributes
      get :show, {:id => consul.to_param}, valid_session
      assigns(:consul).should eq(consul)
    end
  end

  describe "GET new" do
    it "assigns a new consul as @consul" do
      get :new, {}, valid_session
      assigns(:consul).should be_a_new(Consul)
    end
  end

  describe "GET edit" do
    it "assigns the requested consul as @consul" do
      consul = Consul.create! valid_attributes
      get :edit, {:id => consul.to_param}, valid_session
      assigns(:consul).should eq(consul)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Consul" do
        expect {
          post :create, {:consul => valid_attributes}, valid_session
        }.to change(Consul, :count).by(1)
      end

      it "assigns a newly created consul as @consul" do
        post :create, {:consul => valid_attributes}, valid_session
        assigns(:consul).should be_a(Consul)
        assigns(:consul).should be_persisted
      end

      it "redirects to the created consul" do
        post :create, {:consul => valid_attributes}, valid_session
        response.should redirect_to(Consul.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved consul as @consul" do
        # Trigger the behavior that occurs when invalid params are submitted
        Consul.any_instance.stub(:save).and_return(false)
        post :create, {:consul => { "data" => "invalid value" }}, valid_session
        assigns(:consul).should be_a_new(Consul)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Consul.any_instance.stub(:save).and_return(false)
        post :create, {:consul => { "data" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested consul" do
        consul = Consul.create! valid_attributes
        # Assuming there are no other consuls in the database, this
        # specifies that the Consul created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Consul.any_instance.should_receive(:update_attributes).with({ "data" => "MyString" })
        put :update, {:id => consul.to_param, :consul => { "data" => "MyString" }}, valid_session
      end

      it "assigns the requested consul as @consul" do
        consul = Consul.create! valid_attributes
        put :update, {:id => consul.to_param, :consul => valid_attributes}, valid_session
        assigns(:consul).should eq(consul)
      end

      it "redirects to the consul" do
        consul = Consul.create! valid_attributes
        put :update, {:id => consul.to_param, :consul => valid_attributes}, valid_session
        response.should redirect_to(consul)
      end
    end

    describe "with invalid params" do
      it "assigns the consul as @consul" do
        consul = Consul.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Consul.any_instance.stub(:save).and_return(false)
        put :update, {:id => consul.to_param, :consul => { "data" => "invalid value" }}, valid_session
        assigns(:consul).should eq(consul)
      end

      it "re-renders the 'edit' template" do
        consul = Consul.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Consul.any_instance.stub(:save).and_return(false)
        put :update, {:id => consul.to_param, :consul => { "data" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested consul" do
      consul = Consul.create! valid_attributes
      expect {
        delete :destroy, {:id => consul.to_param}, valid_session
      }.to change(Consul, :count).by(-1)
    end

    it "redirects to the consuls list" do
      consul = Consul.create! valid_attributes
      delete :destroy, {:id => consul.to_param}, valid_session
      response.should redirect_to(consuls_url)
    end
  end

end
